site_name: É Foda Bê - Ulduar Guide
theme:
  name: material
  palette:
    scheme: slate
    primary: light blue
    accent: cyan  
  features:
    - navigation.top
plugins:
  - search
  - tags
markdown_extensions:
  - admonition

nav:
  - Index: index.md
  - Normal Mode:
    - Flame Leviathan: normal/flame_leviathan.md
    - Razorscale: normal/razorscale.md
    - Ignis the Furnace Master: normal/ignis.md
    - XT-002: normal/xt002.md
  - Hard Mode:
    - Flame Leviathan: hard/flame_leviathan.md
    - XT-002: hard/xt002.md
